version: '2'
services:
  web:
    build: ./web/
    volumes:
      - "./web:/src/app"
    ports:
      - "9000:9000"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.4
    tty: true

  moses_api:
    build: ./Moses-API/
    volumes:
      - data-volume:/var/lib/moses_api_backup
    ports:
      - "5000:5000"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.5

  corpus_preparation_upload:
    build: ./CorpusPreparationUpload/
    volumes:
      - data-volume:/var/lib/moses_api_backup
    ports:
      - "9001:9000"
    networks:
      vpcbr:
        ipv4_address: 10.6.0.6
    tty: true


volumes:
  data-volume:

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.6.1.0/16
         gateway: 10.6.0.1
