version: '2'
services:
  web:
    build: ./app/
    volumes:
      - "./app:/src/app"
    ports:
      - "3030:3000"
    networks:
      static-network:
        ipv4_address: 172.20.128.2

  moses_api:
    build: ./Moses-API/

    volumes:
      - data-volume:/var/lib/moses_api_backup
    ports:
      - "5000:5000"
    networks:
      static-network:
        ipv4_address: 172.20.129.2

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24

volumes:
  data-volume:
